// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyJSON, config, cors, io, koa, router, server, uFCoder;

  koa = require('koa');

  cors = require('koa-cors');

  router = require('koa-router')();

  bodyJSON = require('koa-parse-json');

  app = koa();

  server = require('http').Server(app.callback());

  io = require('socket.io')(server);

  config = require('./config/app.json');

  uFCoder = new (require('./uFCoder/ufcoder'))(io);

  router.post('/write', bodyJSON(), function*(next) {
    var data;
    data = JSON.stringify(this.request.body);
    this.body = null;
    this.body = (yield uFCoder.linearWrite(data));
    (yield uFCoder.readerUISignal(0, 3));
    return (yield next);
  });

  router.get('/test', function*(next) {
    this.body = 'test';
    return (yield next);
  });

  app.use(cors());

  app.use(function*(next) {
    var error, error1;
    try {
      return (yield next);
    } catch (error1) {
      error = error1;
      this.status = error.status || 500;
      return this.body = {
        statusCode: this.status,
        message: error.message
      };
    }
  });

  app.use(router.routes());

  server.listen(config.port, config.host);

}).call(this);
